server:
  port: 8080
  tomcat:
    max-connections: 20
    threads:
      max: 20
      min-spare: 10
    accept-count: 10

# 微信公众号对接
weixin:
  config:
    originalid: gh_2ba5efe1e9cc
    token: ztw1124
    app-id: wxf8ab74e4ca4a0e00
    app-secret: 20b786fba29a23f2dd9bf6a266d18768
    template_id: RbEZ2jo47dQmF4A7_Ku7RsDy1x_5by6bk1Ox6rPCl4Y

spring:
  datasource:
    username: root
    password: ztw1124
    url: jdbc:mysql://127.0.0.1:3306/s-pay-mall?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat
  # RabbitMQ 配置
  rabbitmq:
    addresses: 127.0.0.1
    port: 5672
    username: admin
    password: admin
    listener:
      simple:
        prefetch: 1 # 每次投递n个消息，消费完在投递n个
#mybatis:
#  mapper-locations: classpath:/mybatis/mapper/*.xml
#  #config-location:  classpath:/mybatis/config/mybatis-config.xml
#  configuration:
#    #开启驼峰命名
#    map-underscore-to-camel-case: true
# 支付宝支付 - 沙箱 https://opendocs.alipay.com/common/02kkv7
alipay:
  enabled: true
  app_id: 9021000141638935
  merchant_private_key: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDrGcgjaMhHbJO4qS9jFo26e/mLElMrSON9sTzA+N1SzuE0TdijAf0mUUn1AknQ6fvnCOMVTdzPnCvQ06PnpQdIWJQmovGfpGjc+ryrGf32+kst5HgtoWxsCqL8vtxmLLsIAhnN9AJld16VSw+ldZWb6TSTW6OKKi6eF81u2bfjEa8GhWVLtShD1RRfyfPaXr9xFD1Y1172zRGgcPIT7+5EQry169voOpfcHa+IcwtuobLQE9bRfdLIiSkITKyHIFCSpzoYSX4tCH9MTPrVM08LHZV3ba3ehatnPYDQCLoFZzZWjeenk8369jhUTS8NVs7Xg3POtcrwy4J1yrwpdHWxAgMBAAECggEBAMmFH/i6KHKQr07qNqRJANOI0S5UVtYTdGyZL+p5Z71Dd+bNk5Smb8gYhbxuabeZ2UMAayYnx85tn2ExCJ3W55cr1lIH+fVNiFVi17YSYY8CnM6JuDnk1HsH4w2izGkIjokew9+1+RfgakKuRIsfb05lZ5uoQVZ9MdhxrrYGCYmoSiCoHZTrUTWcKgmMBe6P54kuQNdo1XayV6CIQRImVb+cuIY70EJcMGzQSsUgUjCZeAyMfSdvps7EYciL1wwEa2EwzFJw1fux0PbX1e4XCemLWfwDtrTCtP8e3wkecdmYgtqsZS1rl4DdQRU8f/0ZVIYAZo5ritj+Hxw2sQmxOQECgYEA+sVBQLu/80xZOiBPe36zZRFj/dw7Ta/EFtahzoOh8dMNZn1n1/lt7yoDGdYGbPNlO8oAXDlsPhCd8HaU65Qc+yjA1v3s0U3mptkoJlq4WZqvHiTFjn+JxXq48tdkT/TfrfzRXV9mROGO7VqG81w/y6CCCpM68AG4OU7JSpJv20UCgYEA8ADfh6pijK19BVBd4+4zBINRH3Orihj9r4c9TeEPK+HGneGn2/wDVOB5Q9z0kdz12FYKr12bP//6v8Pkq59m079fShQtY4lG+UtdpPwPz+LPIjLzI2pjdsuLDWNTk3Fib4uc5XPG2cIH/F0FWkWSmAjm0DEd2RcjEjOFNhcwoX0CgYEAsRrQu/QdW6onNisNl21jK1T95pM8euBQv8Rz4FMM86oXw7N7vIeXgZqNOBj0zsuTSoeee4O+k5LOyL4m7L3dPfCJSQ1qzGOVK28gsP3PRtE9Li/QKpSea48BwdgnK2UI+GsePjCbHLikZbNSrdsP3zMLxIY40LqWLjsbZIRJZXUCgYASNi7AD6jMvflnptKJEjEi3YgRV+ijYQQXBq8bMsHA9a/pmQ7wvW3PSf1JrgGM8/Rfxx+mcPbv40+2r3mxoDXgSXxElcVf8THGhvaDJ3FXuAE5uh4DCPalNArIKEpWPNtYVYLBUoi7S2LpvnFCiVb3XG2PTLrUF1Jc9jXcheP1zQKBgFbL+Xs5UF0WOIf30GKjc49eQhQDj/D4x9bl44pU/1h6JbJSRXXZUzD2jMcrAn4Ug7cpLYX4aSxdoTo4LNNSeGltElXIb9dmkJX7crJ0YH1bT+N/2pTT8VkIQ8oZwQ9p6Jb1sxZ/OGmA3l25VWFrls/+NMMaew5tsUaV8qBS9/mp
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAn8tD/om51+o16d07pTTlTmYwdcC6qv4Z2NHUc+xBDjvKjvIBxuURfCPUuGg0oxY9WgMp7tasYJqcVPl5xSgYNHSo1V2FTAyIc+hkDvf3j1puhHZrplpg//nK7t8S8yROqk74RIFVKUWgFwl/bkyKDI/Zi8VvKNUsbzYVzyIjRaEI/X7lA+P1Cb0LPquIqZ1plwnliSDUIYed8NPQsGfy00Ts3xVcWgIoFFDOMP8DNpHkGDYeakoOcaXEn3qx6Yx+AgApHhNlPpLlHxHxiTIRRYezsK+aZPKqWNzys7Tun1nsdZf/KtMsLy7LbuEVeB0XTJ6sC8N28oO6cjvd7AKnpQIDAQAB
  notify_url: http://ztw1124.natapp1.cc/api/v1/alipay/alipay_notify_url
  return_url: https://gaga.plus
  gatewayUrl: https://openapi-sandbox.dl.alipaydev.com/gateway.do

# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml

redis:
  sdk:
    config:
      host: 127.0.0.1
      port: 16379
      pool-size: 10
      min-idle-size: 5
      idle-timeout: 30000
      connect-timeout: 5000
      retry-attempts: 3
      retry-interval: 1000
      ping-interval: 60000
      keep-alive: true
